### ISSUE TITLE
Spectator mode and bugs.

### ISSUE THREAD

**Issue by MustafaEsatTemel** [TroDerp/EggWars#15]
Hi bro can u add spectator mode for eggwars. For example if the game has started, then when players click the sign(in_game) they can watch our game.
Also 1.16.5 version has bug (If you try to place block to egg its occurs)
1.17 signs not working very well.
![image](https://github.com/user-attachments/assets/40d431cd-1748-4ff0-887d-5caaebb8cc84)

**Comment by TroDerp** [comment]
Hi Mustafa, to make players able to spectate active games, you have to set config.yml option `spectator`>`can_enter_ingame` to `true`. For the bug with placing block to the dragon egg, this will be fixed for next patch soon. However, for the sign bug I need more information, you say it only affects 1.17 or all versions? I fixed a bug with them but I'm not sure if it's the same one as that affects all versions. Thanks for you patience.

**Comment by MustafaEsatTemel** [comment]
> Hi Mustafa, to make players able to spectate active games, you have to set config.yml option `spectator`>`can_enter_ingame` to `true`. For the bug with placing block to the dragon egg, this will be fixed for next patch soon. However, for the sign bug I need more information, you say it only affects 1.17 or all versions? I fixed a bug with them but I'm not sure if it's the same one as that affects all versions. Thanks for you patience.

Im not sure for sign bug version dude, i wrote these message like 1 month ago i forgot it :/

**Comment by TroDerp** [comment]
Don't worry, I'll do some testing in these versions and try to close this asap.

**Comment by TroDerp** [comment]
Fix tested and bug solved.
